version: '3.8'

services:
  mysqldb:
    platform: linux/x86_64
    image: mysql:8.0
    restart: unless-stopped
    env_file: ./.env.prod
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
    ports:
      - $MYSQLDB_PORT:3306
    volumes:
      - ./data/:/var/lib/mysql
  api:
    env_file: ./.env.prod
    build: .
    container_name: weni-locals
    links:
      - "mysqldb:mysqldb"
    ports:
      - 3000:3000
    
