apiVersion: apps/v1
kind: Deployment
metadata:
  name: wine-locals-dp
spec:
  replicas: 5
  selector:
    matchLabels:
      app: wine-locals
  template:
    metadata:
      labels:
        app: wine-locals
    spec:
      containers:
      - name: wine-locals-api
        image: devtfo/wine-locals:test-1.0.1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 4568
        env:
          - name: DATABASE_URL
            value: "mysql://root:senha_root_123@wine-locals-db:3306/wine-locals"